import Head from 'next/head';
import WeatherForecast from '../components/WeatherForecast';
import axios from 'axios'
import { useState } from 'react';

const torontoCoordinates = {
  long: -79.3832,
  lat: 43.6532,
}

export async function getStaticProps() {
  const apiKey= process.env.OPEN_WEATHER_API_KEY;

  const res = await axios.get(`https://api.openweathermap.org/data/2.5/weather?lat=${torontoCoordinates.lat}&lon=${torontoCoordinates.long}&appid=${apiKey}&units=metric`);
  
  const data = res.data;
  return {
    props: {
      data: data,
    }, 
  }
}

export default function Home({ data } : {data : {}}) {
  const [user, setUser] = useState(undefined);

  return (
    <>
      <Head>
        <title>Greenhouse App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          user && 
          <div>
            Hi, {user}! 
          </div>
        }
        <div>
          <WeatherForecast data={data} />
        </div>
      </main>
    </>
  )
}
